# Generated by Django 4.2.7 on 2026-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='click_power',
            field=models.IntegerField(default=1),
        ),
    ]
